---
name: NPM Install, Build, and Cache
description: NPM Install Dependencies, NPM Run Build, and Cache Build Artifacts

runs:
  using: "composite"
  steps:
    - name: Set up nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Cache Turbo build outputs
      uses: actions/cache@v4
      id: cache-turbo-build
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-build-

    - name: Build
      shell: bash
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          packages/**/build/*
          e2e-tests/build/*
          github-pages-publisher/build/*
        if-no-files-found: error
