body:
  - type: textarea
    attributes:
      label: What do you need help with?
      description: Describe what you are trying to achieve or need help understanding.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description:
        Please add any extra details or references that may provide useful context for this discussion.
    validations:
      required: false
