body:
  - type: textarea
    attributes:
      label: What is your idea?
      description: Add a short list of what your feature request or idea aims to address.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it important?
      description:
        Discuss prior art and why you think this addition is needed. Are there current alternatives?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What do you propose?
      description: Describe how this should be implemented. Would you be interested in contributing?
    validations:
      required: true
