name: Common CI Jobs

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "NPM Install, Build, and Cache"
        id: npm-install-build-and-cache
        uses: ./.github/actions/npm-install-build-and-cache

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Test
        uses: ./.github/actions/run-turbo-task
        with:
          task: test-all

  type-check:
    name: Type Check
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Type Check
        uses: ./.github/actions/run-turbo-task
        with:
          task: type-check-all

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Lint
        run: npm run lint-all
