name: Common CI Jobs

on:
  workflow_call:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "NPM Install, Build, and Cache"
        id: npm-install-build-and-cache
        uses: ./.github/actions/npm-install-build-and-cache

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Test
        run: npm run test-all

  type-check:
    name: Type Check
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Type Check
        run: npm run type-check-all

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Lint
        run: npm run lint-all

  # TODO: Re-enable (https://github.com/mml-io/mml/issues/241)
  # e2e-test-playcanvas:
  #   name: End-to-end Test (PlayCanvas)
  #   needs: build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.cache
  #         key: ${{ runner.os }}

  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #         persist-credentials: false

  #     - name: "Retrieve Dependencies and Build Artifacts"
  #       id: retrieve-deps-and-build
  #       uses: ./.github/actions/retrieve-deps-and-build

  #     - name: End to End Test
  #       run: npm run ci:e2e-tests:playcanvas

  #     - name: Upload End to End Test Images
  #       if: failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: images-playcanvas
  #         path: e2e-tests/test/__image_snapshots__/__diff_output__/

  e2e-test-threejs:
    name: End-to-end Test (ThreeJS)
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache
          key: ${{ runner.os }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: End to End Test
        run: npm run ci:e2e-tests:threejs

      - name: Upload End to End Test Images
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: images-threejs
          path: e2e-tests/test/__image_snapshots__/__diff_output__/
