name: Main

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  ci:
    name: Common CI Jobs
    uses: ./.github/workflows/ci-common.yaml

  summary:
    name: Summary
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "Common CI Jobs: ${{ needs.ci.result }}"
